apiVersion: v1
kind: ConfigMap
metadata:
  name: devzat-config
  labels:
    k8s-app: devzat
    kubernetes.io/cluster-service: "true"
data:
  devzat-config.yml: |
    port: 22
    alt_port: 443
    profile_port: 5555
    key_file: devzat-sshkey
    data_dir: devzat-data
    admins:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devzat-deployment
  labels:
    app: devzat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devzat
  template:
    metadata:
      labels:
        app: devzat
    spec:
      containers:
      - name: devzat
        image: inerplat/devzat:main
        imagePullPolicy: Always
        ports:
          - containerPort: 443
        volumeMounts:
          - name: devzat-config
            mountPath: /app/devzat-config.yml
            subPath: devzat-config.yml
      volumes:
        - name: devzat-config
          configMap:
            name: devzat-config
---
apiVersion: v1
kind: Service
metadata:
  name: devzat-svc
spec:
  type: NodePort
  selector:
    app: devzat
  ports:
    - port: 443
      targetPort: 443
      nodePort: 32443
