apiVersion: apps/v1
kind: Deployment
metadata:
  name: devzat-deployment
  labels:
    app: devzat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devzat
  template:
    metadata:
      labels:
        app: devzat
    spec:
      containers:
      - name: devzat
        image: inerplat/devzat:main
        imagePullPolicy: Always
        ports:
          - containerPort: 443
#        command:
#         - tail
#        args:
#          - -f
#          - /dev/null
---
apiVersion: v1
kind: Service
metadata:
  name: devzat-svc
spec:
  type: NodePort
  selector:
    app: devzat
  ports:
    - port: 443
      targetPort: 443
      nodePort: 32443